# fly.toml app configuration file generated for olmocr-backend on 2025-10-04T16:30:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'olmocr-backend'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  ENVIRONMENT = "production"
  DEBUG = "false"
  API_V1_PREFIX = "/api/v1"
  DOCS_URL = "/docs"
  REDOC_URL = "/redoc"
  LOG_LEVEL = "INFO"
  LOG_FORMAT = "json"
  TEMP_STORAGE_PATH = "/app/temp_storage"
  MAX_FILE_SIZE_MB = "10"
  MAX_BATCH_SIZE = "10"
  FILE_RETENTION_HOURS = "24"
  CLEANUP_INTERVAL_HOURS = "1"
  REDIS_MAX_CONNECTIONS = "20"
  REDIS_CONNECT_TIMEOUT = "10"
  REDIS_SOCKET_TIMEOUT = "30"
  CELERY_WORKER_CONCURRENCY = "2"
  SUPABASE_STORAGE_BUCKET = "jobs"
  CORS_ALLOW_CREDENTIALS = "true"
  CORS_ALLOW_METHODS = "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOW_HEADERS = "*"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
